### ISSUE TITLE
Add --do-not-minimize option to hfst-regexp2fst

### ISSUE THREAD

**Issue by hfst-importer** [hfst/hfst#290]
Would it be possible to add an option to NOT do implicit minimisation in hfst-regexp2fst? As it is now, minimisation is done automatically and unconditionally AFAICS, and that blows up certain fst’s, especially error models for spellers. The error models are pretty simple from a regex/fst point of view, but minimisation is doing the opposite of the intention for them - making the fst's huge instead of smaller. It also slows down compilation quite a bit

Reported by: snomos

**Comment by snomos** [comment]
I tried the new version with this change implemented, and I get the following error:

```
$ /usr/local/bin/hfst-regexp2fst --do-not-minimize -S editdist.default.regex -o editdist.default.hfst
editdist.default.regex.3: XRE parsing failed
```

Without the --do-not-minimize option, the regex compiles without issues.

**Comment by snomos** [comment]
Regex file to reproduce buggy behavior.

[editdist.default.regex.zip](https://github.com/hfst/hfst/files/460260/editdist.default.regex.zip)

**Comment by eaxelson** [comment]
There was a typo in option processing, now --do-not-minimize works. However, determinization instead of minimization seems to have a negative effect both on speed and size of result:

> yes, no speed difference in compilation time, and resulting fst 3x bigger
so we’ll stick with minimisation
time /usr/local/bin/hfst-regexp2fst --do-not-minimize -S editdist.default.regex -o editdist.default.hfst
real 4m53.029s
time /usr/local/bin/hfst-regexp2fst -S editdist.default.regex -o editdist.default.hfst
real 0m26.310s
