### ISSUE TITLE
hfst-tokenize -S doesn't affect --cg

### ISSUE THREAD

**Issue by TinoDidriksen** [hfst/hfst#350]
hfst-tokenize -S doesn't affect --cg

(@unhammer)

**Comment by unhammer** [comment]
Actually, it does – it's just that [print_nonmatching_sequence](https://github.com/hfst/hfst/blob/master/tools/src/hfst-tokenize.cc#L160) for --cg puts anything non-matching inside a word form, e.g. 

```
$ echo '[ ja ]ja' |hfst-tokenise -S --cg sme-nob.automorf.hfst
"<[ ja ]>"
        "[ ja ]" ?
"<ja>"
        "ja"<cnjcoo>
        "ja"

$ echo '! ja' |hfst-tokenise --cg -S -a sme-nob.automorf.hfst
"<! >"
        "! " ?
"<ja>"
        "ja"<cnjcoo>
        "ja"

"<
>"
        "
" ?
```

I didn't write the --cg format, so I think whoever actually uses it should chime in. 

Making it similar to --giella-cg would be possible with just `output_format == giella_cg || output_format == cg` in L162 and then removing L160..161. 

-----

Note that there are other important differences too, e.g. --giella-cg also treats words-without-analyses as unknowns, giving a reading with a `?` as the only tag, whereas --cg gives no readings for unknowns. I don't know if we want --cg to do that or what. 

And perhaps more importantly, --giella-cg treats as lemma everything up to the first *multichar* symbol with an initial/final `+` – an assumption about a certain convention of writing lexc's. The --cg format, OTOH, hopes that the lemma equals the form, otherwise just uses the FST output as-is (assuming that the FST/lexc inserts literal `"`'s around lemmas and spaces around tags).

**Comment by TinoDidriksen** [comment]
Oh, well then, I'll just ignore `--cg` in favour of `--giella-cg` for now.
