### ISSUE TITLE
Ospell does not accept all strings that it suggest itself for lut; there seems to be an irregularity with combining diacritics.

### ISSUE THREAD

**Issue by rueter** [hfst/hfst#373]
The Lushootseed (lut) language is partially supported by ospell, but it seems not all multi-character symbols have been put into the code, perhaps.

Evidence can be observed in the the jpg; there seem to be some combining diacritics and modifier letters that are not accepted by ospell but are indeed suggested by ospell.

For example letter with the combining U+0313 are not accepted, but those with U+0315 are.

[lut.zhfst.zip](https://github.com/hfst/hfst/files/1479831/lut.zhfst.zip)

![lut-ospell-does-not-accept-what-it-suggests_2017-11-16](https://user-images.githubusercontent.com/14276164/32909763-1184ecea-cb10-11e7-934f-6ad32fa88349.jpg)

**Comment by Traubert** [comment]
Hm. I can verify that the acceptor alphabet does contain U+0313 and it does contain sup̓qs. What I think is happening is this:

- the acceptor contains U+0313 both as a standalone character and composed with various other alphabetic characters

- the error model doesn't contain U+0313 as a standalone character, but it does have it composed with other characters

- the acceptor has a valid bath for sup̓qs when it tokenizes p̓ as one symbol, but not when it tokenizes it as two

- the error model will emit the one-symbol p̓, because that's all it knows about, and that goes through the lexicon

- when checking for sup̓qs, the p̓ gets tokenized as two symbols because it begins with an ascii character

So what needs to be done to avoid this possibility is a way to avoid this shadowing. In fact I think a similar bug was fixed for optimized-lookup some time ago..

I'll get on this, sorry I didn't pay attention to the bug report earlier.

**Comment by Traubert** [comment]
Incidentally this bug belongs in the hfst-ospell repository and not here, so I'll close it here.
