### ISSUE TITLE
UpCase doesn't work when analyses have flags

### ISSUE THREAD

**Issue by unhammer** [hfst/hfst#429]
``` bash
printf '0\t2\tx\t<xtag>\t0.000000\n0\t1\t@P.Px.add@\t@P.Px.add@\t0.000000\n1\t2\tn\t<ntag>\t0.000000\n2\n' \
  | hfst-txt2fst >/tmp/n.hfst
hfst-fst2strings /tmp/n.hfst
```
gives
```
x:<xtag>
n:<ntag>
```
and
```bash
hfst-fst2strings --xfst=print-flags /tmp/n.hfst
```
gives
```
x:<xtag>
@P.Px.add@n:@P.Px.add@<ntag>
```

but when adding the upcased version
```bash
hfst-pmatch2fst <<< 'set need-separators off regex UpCase(@bin"/tmp/n.hfst", U);' >/tmp/n.pmhfst
echo X x N n | hfst-tokenise  -x /tmp/n.pmhfst
```
only the non-flagged analysis is included:

```
X       <xtag>


```

@Traubert should UpCase work across flags?

**Comment by Traubert** [comment]
I suspect the problem here is that composition does not harmonize flag diacritics, by design. It is apparently impossible to remember all our design decisions around flag diacritics and not write bugs..

Here's the relevant part in `libhfst/src/parsers/pmatch_utils.cc`:

```C++
    HfstTransducer anything(hfst::internal_identity, hfst::pmatch::format);
    if (optional == false) {
        anything.subtract(*latin1_lowercase_acceptor);
    }
...
    } else if (side == Upper) {
        retval = new HfstTransducer(*lowerfy);
        retval->disjunct(anything);
        retval->repeat_star();
        retval->compose(t);
```

So we're trying to accept "anything" (the disjunction with `anything`), and convert what `lowerfy` (because we're on the `U` side) wants to convert, and if we're not an `OptUpCase`, we disallow latin1 lowercase from "anything". The problem is that when we finally compose with our target `t`, the flag diacritics don't get expanded into the `?` of `anything`, because we normally don't want to harmonize flag diacritics, just insert them into the alphabet.

So the easy solution would be to manually grab the flag diacritics from `t` and disjunct them with `anything` first. I can do that as a band-aid solution at least. A perhaps better solution would be to support this sort of situation in the library better. I will have a bit of a think about this.

@eaxelson , something for you to think about too!

**Comment by Traubert** [comment]
My meditations are now complete and I have discovered that the global variable `hfst::xerox_composition` controls this behaviour. Setting it `true` in `cap`, `tolower` and `toupper` fixes this bug, and I have now done so, though still taking care to set it back at the end of the functions, possibly leaving behind other bugs where we should be using `hfst::xerox_composition` too.
