### ISSUE TITLE
Lemma misprinted in hfst-tokenise -g when using -m

### ISSUE THREAD

**Issue by snomos** [hfst/hfst#440]
Symptom:

```
$ echo 'са̄в'  | hfst-tokenise --giella-cg -W tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
"<са̄в>"
	"са̄в" ?
:\n
$ echo 'са̄в'  | hfst-tokenise --giella-cg -W -m tools/tokenisers/tokeniser-disamb-gt-desc.pmhfst 
"<са̄в>"
	"с"а̄"в" A
	"с"а̄"в" N Sg Nom
:\n
```

The issue at hand is related to accented chars & combining diacritics, cf bug #367. Without the `-m` option, the accented input is not analysed, with the `-m` option it works fine - almost.

The remaining issue is that the lemma is broken up around the letter with the dynamic compound, as seen above.

To reproduce:
```
$ cd $GTHOME/langs/smn
$ ./configure --with-hfst --without-xfst --enable-tokenisers
$ make -j
```

Setup:

* newest hfst (nightly)
* newest macOS

**Comment by unhammer** [comment]
What language is this? (I didn't think smn used cyrillic?)

**Comment by unhammer** [comment]
I've managed to reproduce in https://github.com/hfst/hfst/issues/367#issuecomment-562598381 , 

```
$ echo ' Na' |hfst-tokenize -g -m spacen.pmhfst
"< Na>"
         N"a" <W:2.0>
:\n
```

The reason for the extra "'s is that before we had `--tokenize-multichars`, we could treat tags (non-lemmas) as exactly the Multichar_symbols. So any symbol that was longer than one utf-8 codepoint was a tag symbol, not part of any lemma:

https://github.com/hfst/hfst/blob/master/libhfst/src/implementations/optimized-lookup/pmatch_tokenize.cc#L199-L210

Since tags aren't given any special treatment in HFST, I don't see any simple way of distinguishing them here.  We have two utf-8 codepoints on one arc, on the same side of the FST as the tags are. 

Well, I suppose we could hardcode a set of combining characters, then strip any such off the string before checking that we were left with one utf-8 codepoint. Or, if we have ICU, perhaps we could normalise the string first to NFC first …

**Comment by snomos** [comment]
> What language is this? (I didn't think smn used cyrillic?)

My bad, `smn` was a misspelling for `mns` - Mansi. Muscle memory ...
