### ISSUE TITLE
label push / dealign

### ISSUE THREAD

**Issue by flammie** [hfst/hfst#464]
I have been experimenting in re-writing the guessers in python, see [pyhfst guessify](https://github.com/flammie/pyhfst-guesser), for good naive guesser  the analysis symbols cannot be aligned with normal alphabet, I think openfst's label push might help here if it could be made into a command-line tool?

The actual problem: Given say talo+n+sg+ine:talossa an alignment t:t a:a l:l o:o +n:s +sg:s +ine:a will make suffix guessing hard for the actual suffix and it gets worse on more problematic paradigms, having possibly unaligning it to 0:s 0:s 0:a +n:0 +sg:0 +ine:0 makes everything neater, the problem also occurs in converted apertium dictionaries so having it inside lexc "--alignStrings" does not work.

**Comment by mr-martian** [comment]
This could be done with the algorithm described in #400.

**Comment by ftyers** [comment]
I'm having this same kind of problem working with segmentation. I'm doing segmentation as:

* Compose `surface:lemmatags` with `lemmatags:segmented`, e.g. `wolves:wolf<n><pl>` with `wolf<n><pl>:wolv>es`.

But the problem is that sometimes there are surface forms which are variants like `wolfs:wolf<n><pl>`. So when I use the segmenter I get:
```
wolves        wolv>es
wolves        wolf>s
```

I'd like to remove the `wolves:wolf>s` stringpair, but if I try and do it using:

* Freely insert `0:>` using `[ ? | ? 0:%> ]*` into the surface side of the segmenter to get:
```
...
wolves        wolv>es
wolves        w>olv>es
wolves        wol>ve>s
...
```
etc. 

And then intersect with the original segmenter... I get no output because the pairstrings don't align, e.g. the segmenter might have,
```
w:w o: :o l:l :v v:> e:e s:s
```
and after free-insertion to the surface side, we get:
```
w:w o:o l:l v:v :> e:e s:s
```

**Comment by ftyers** [comment]
@flammie suggested looking at OpenFST's `fstpush`. This can improve the situation, although I'm not sure if it's a complete solution.

Here is an example unaligned transducer:
```
0	1	x	x
1	2	@	>
2	3	i	<eps>
3	4	n	<eps>
4	5	<eps>	i
5	6	<eps>	n
6	7	@	>
7	8	e	<eps>
8	9	ʼ	<eps>
9	10	<eps>	b
10	11	<eps>	ʼ
11	12	<eps>	e
12	13	@	>
13	14	w	w
14	15	a	a
15	16	ʼ	ʼ
16	17	@	>
17	18	o	o
18	19	q	q
19
```
Note that `<eps>` stands for epsilon and `@` stands for the epsilon on the other side of the morpheme boundary. --- this is needed because otherwise things will end up aligned with the morpheme boundary.

Label push only works on output labels, so we have to run it twice:
```
$ fstcompile --isymbols=isyms.txt --osymbols=osyms.txt --keep_isymbols --keep_osymbols test2.att test2.openfst
$ fstinvert test2.openfst | fstpush --push_labels | fstinvert | fstpush --push_labels | fstminimize | fstepsnormalize | fstprint 
0	1	x	x
1	2	@	>
2	3	i	i
3	4	n	n
4	5	@	>
5	6	e	b
6	7	ʼ	ʼ
7	8	@	e
8	9	w	>
9	10	a	w
10	11	ʼ	a
11	12	@	ʼ
12	13	o	>
13	14	q	o
14	15	<eps>	q
15
```
We'd then have to change the `@` back to `<eps>`. Note that this is an improvement in some senses, and potentially with enough pushing backwards and forwards we can get better alignment?
```
$ fstinvert test2.openfst | fstpush --push_labels | fstinvert | fstpush --push_labels | fstminimize | fstepsnormalize | fstpush --push_labels --to_final | fstinvert | fstpush --push_labels --to_final | fstepsnormalize | fstpush --push_labels | fstepsnormalize | fstprint 
0	1	x	x
1	2	>	@
2	3	i	i
3	4	n	n
4	5	>	@
5	6	b	e
6	7	ʼ	ʼ
7	8	e	@
8	9	>	w
9	10	w	a
10	11	a	ʼ
11	12	ʼ	@
12	13	>	o
13	14	o	q
14	15	q	<eps>
15
```

Thoughts?

**Comment by mr-martian** [comment]
The alignment algorithm in #400 / lexc --alignStrings would give
```
0	1	x	x
1	2	<eps>	>
2	3	@	<eps>
3	4	i	i
4	5	n	n
5	6	<eps>	>
6	7	@	<eps>
7	8	<eps>	b
8	9	e	<eps>
9	10	ʼ	ʼ
10	11	<eps>	e
11	12	<eps>	>
12	13	@	<eps>
13	14	w	w
14	15	a	a
15	16	ʼ	ʼ
16	17	<eps>	>
17	18	@	<eps>
18	19	o	o
19	20	q	q
20
```
I also found that by tweaking the weights you can get all the same matching pairs aligned with fewer epsilons, which would produce:
```
0	1	x	x
1	2	@	>
2	3	i	i
3	4	n	n
4	5	@	>
5	6	e	b
6	7	ʼ	ʼ
7	8	@	e
8	9	<eps>	>
9	10	w	w
11	12	a	a
12	13	ʼ	ʼ
13	14	@	>
14	15	o	o
15	16	q	q
16
```
Though here you do get a `@:e` pair.

**Comment by ftyers** [comment]
Which weights would need to be tweaked? Also, that alignment is pretty great and I think it would work fine for real use-cases. I just realised that this is not a good example because source and target are different surface strings (in fact exactly what I'm trying to get rid of!)... I'll come up with a better example and post it here.

**Comment by ftyers** [comment]
Actually, with the non-broken transducer, the fstpush seems to work:
```
$ fstprint test4.openfst 
0	1	x	x
1	2	@	>
2	3	i	<eps>
3	4	n	<eps>
4	5	<eps>	i
5	6	<eps>	n
6	7	@	>
7	8	e	<eps>
8	9	ʼ	<eps>
9	10	<eps>	e
10	11	<eps>	ʼ
11	12	@	>
12	13	w	w
13	14	a	a
14	15	ʼ	ʼ
15	16	@	>
16	17	o	o
17	18	q	q
18

$ fstinvert test4.openfst | fstpush --push_labels | fstinvert | fstpush --push_labels | fstminimize | fstepsnormalize | fstprint 
0	1	x	x
1	2	@	>
2	3	i	i
3	4	n	n
4	5	@	>
5	6	e	e
6	7	ʼ	ʼ
7	8	@	>
8	9	w	w
9	10	a	a
10	11	ʼ	ʼ
11	12	@	>
12	13	o	o
13	14	q	q
14


```

**Comment by mr-martian** [comment]
lexc --alignStrings is based on Levenshtein distance. In lexc the substitution cost is set to 100 (as a stand-in for infinity), but you can get the more compressed alignment by setting the substitution cost to 1.

See the following for implementations with comments:
https://github.com/hfst/hfst/blob/265bc37a8fc61726f6665b31b82b0214d9b492e0/libhfst/src/parsers/lexc-utils.h#L114
https://github.com/hfst/hfst/blob/265bc37a8fc61726f6665b31b82b0214d9b492e0/libhfst/src/parsers/lexc-utils.cc#L458
https://github.com/apertium/lexd/blob/239f366f3236326fdb99883675fbc756a05fb0c2/src/lexdcompiler.cc#L994

**Comment by ftyers** [comment]
So maybe it could work by something like:

http://www.openfst.org/twiki/bin/view/FST/PushDoc

```
const uint32 kPushWeights = 0x0001;
const uint32 kPushLabels =  0x0002;

enum ReweightType { REWEIGHT_TO_INITIAL, REWEIGHT_TO_FINAL };

template<class Arc>
void Invert(MutableFst<Arc> *fst);

template <class Arc, ReweightType rtype>
void Push(const Fst<Arc> &ifst, MutableFst<Arc> *ofst, uint32 ptype)

template<class Arc>
void Invert(MutableFst<Arc> *fst);

template <class Arc, ReweightType rtype>
void Push(const Fst<Arc> &ifst, MutableFst<Arc> *ofst, uint32 ptype)
```

**Comment by ftyers** [comment]
There is some code for pushing weights in the interface already:
```
HfstTransducer &HfstTransducer::push_weights(PushType push_type)
{
#if HAVE_OPENFST
    bool to_initial_state = (push_type == TO_INITIAL_STATE);
    if (this->type == TROPICAL_OPENFST_TYPE)
    {
        hfst::implementations::StdVectorFst * tmp  =
        this->tropical_ofst_interface.push_weights
        (this->implementation.tropical_ofst, to_initial_state);
        this->tropical_ofst_interface.delete_transducer(this->implementation.tropical_ofst);
        this->implementation.tropical_ofst = tmp;
        return *this;
    }
#if HAVE_OPENFST_LOG
    if (this->type == LOG_OPENFST_TYPE)
    {
        hfst::implementations::LogFst * tmp =
        this->log_ofst_interface.push_weights
        (this->implementation.log_ofst, to_initial_state);
        this->log_ofst_interface.delete_transducer(this->implementation.log_ofst);
        this->implementation.log_ofst = tmp;
        return *this;
    }
#endif
#endif
    (void)push_type;
    return *this;
}
```

`libhfst/src/HfstTransducer.cc`
```
