### ISSUE TITLE
hfst-info: symbol lookup error

### ISSUE THREAD

**Issue by GooDeeJaY** [hfst/hfst#566]
Followed wiki tutorial: [Download and install HFST](https://github.com/hfst/hfst/wiki/Download-And-Install#installing-hfst-to-linux)

When I ran `hfst-info`, I got an error:

    hfst-info: symbol lookup error: /lib/x86_64-linux-gnu/libhfst.so.55: undefined symbol: fsm_set_option

**Comment by GooDeeJaY** [comment]
I'm using Ubuntu 20.04 LTS (WSL 2) on Windows

Retried downloading and running `install-nightly.sh` again, but to no avail.

Then, I tried manually installing 0.10.0 version of libfoma0:

    sudo apt-get install libfoma0=0.10.0+s305-3~focal1

Now, it is working:
```
$ hfst-info
No tests selected; printing known data
HFST info version: 0.1
HFST packaging: hfst 3.16.0
HFST version: 3.16.0
HFST long version: 300160000
OpenFst supported
SFST supported
foma supported
Unicode support: ICU
```

Thanks!

**Comment by Trondtr** [comment]
It seems closing this issue is a bit too "now it works for me" to be an optimal solution. I havwe collegues in my team using the same configuration (Linux on Windows) and getting the same error. It is of course nice to know that writing `sudo apt-get install libfoma0=0.10.0+s305-3~focal1` solves the issue (one solution is way better than no solution), but I sort of hope  it will work directly from `install-nightly`, as before.

**Comment by TinoDidriksen** [comment]
The install-nightly script does this, and has done this for years. It installs a preference so that the "older" Foma from nightly is preferred and installed instead of the one from the distro.

So the only way to run into this problem is to circumvent the install-nightly helper.

**Comment by Trondtr** [comment]
Ok. It seems we need a section **Troubleshooting** on this page:

[giellalt.github.io/infra/GettingStartedOnWindows.html](https://giellalt.github.io/infra/GettingStartedOnWindows.html)

I will add it. Feel free to comment if I have misunderstood something. I will present it as a problem arriving from above.
